// Quiz Questions Database - 25+ Fragen zum Thema Lost Places / Urban Exploring
const quizQuestions = [
    // GRUNDLAGEN
    { id: 1, category: "Grundlagen", difficulty: "easy", question: "Was bedeutet die Abkürzung 'Urbex'?", answers: ["Urban Exploring", "Urban Experience", "Urban Exhibition", "Urban Exit"], correct: 0, explanation: "Urbex steht für 'Urban Exploring' - das Erkunden urbaner, oft verlassener Orte." },
    { id: 2, category: "Grundlagen", difficulty: "easy", question: "Was ist ein 'Lost Place'?", answers: ["Ein vergessener Treffpunkt", "Ein verlassenes Gebäude oder Gelände", "Ein Kartenfehler", "Ein versteckter Club"], correct: 1, explanation: "Lost Places sind verlassene Orte wie alte Fabriken, Krankenhäuser oder Militäranlagen." },
    { id: 3, category: "Grundlagen", difficulty: "easy", question: "Was bedeutet 'Take nothing but pictures, leave nothing but footprints'?", answers: ["Nur fotografieren, nichts mitnehmen oder hinterlassen", "Schnell rein und raus", "Gute Schuhe tragen", "Selfies sind verboten"], correct: 0, explanation: "Diese goldene Regel bedeutet: Nimm nichts mit und hinterlasse nichts außer Fußspuren." },
    { id: 4, category: "Grundlagen", difficulty: "medium", question: "Was ist der Unterschied zwischen Urbex und Geocaching?", answers: ["Kein Unterschied", "Urbex erkundet verlassene Orte, Geocaching sucht versteckte Behälter", "Geocaching ist illegal", "Urbex ist nur nachts"], correct: 1, explanation: "Geocaching ist eine GPS-Schatzsuche, Urbex ist das Erkunden verlassener Orte." },
    { id: 5, category: "Grundlagen", difficulty: "easy", question: "Welches dieser Objekte ist KEIN typischer Lost Place?", answers: ["Verlassene Fabrik", "Altes Krankenhaus", "Aktives Einkaufszentrum", "Stillgelegter Freizeitpark"], correct: 2, explanation: "Ein aktives Einkaufszentrum ist kein Lost Place, da es noch in Betrieb ist." },

    // SICHERHEIT
    { id: 6, category: "Sicherheit", difficulty: "easy", question: "Warum sollte man nie alleine einen Lost Place betreten?", answers: ["Es ist langweilig alleine", "Falls etwas passiert, kann jemand Hilfe holen", "Alleine ist es legal", "Man braucht jemanden für Fotos"], correct: 1, explanation: "Sicherheit geht vor! Bei Unfällen kann ein Begleiter lebensrettend sein." },
    { id: 7, category: "Sicherheit", difficulty: "easy", question: "Welches Ausrüstungsteil ist beim Urbex am wichtigsten?", answers: ["Kamera", "Taschenlampe", "Snacks", "Spraydose"], correct: 1, explanation: "Eine zuverlässige Taschenlampe ist essentiell, da viele Lost Places dunkel sind." },
    { id: 8, category: "Sicherheit", difficulty: "medium", question: "Was ist Asbest und warum ist es gefährlich?", answers: ["Ein Insekt in alten Gebäuden", "Ein krebserregender Baustoff in älteren Gebäuden", "Ein Pilz auf altem Holz", "Ein giftiges Gas"], correct: 1, explanation: "Asbest wurde früher als Dämmstoff verwendet und kann bei Einatmung Krebs verursachen." },
    { id: 9, category: "Sicherheit", difficulty: "hard", question: "Was solltest du tun, wenn du Anzeichen von Asbest entdeckst?", answers: ["Probe mitnehmen", "Sofort den Bereich verlassen", "Fenster öffnen", "Foto machen und weitergehen"], correct: 1, explanation: "Bei Asbestverdacht solltest du den Bereich sofort verlassen und nicht stören." },
    { id: 10, category: "Sicherheit", difficulty: "medium", question: "Welche Schutzausrüstung ist bei alten Industrieanlagen empfehlenswert?", answers: ["Nur gute Schuhe", "Staubmaske, feste Schuhe, Handschuhe, Taschenlampe", "Schwimmweste", "Helm und Warnweste"], correct: 1, explanation: "Alte Industrieanlagen können Schadstoffe enthalten - Schutzausrüstung ist wichtig!" },
    { id: 11, category: "Sicherheit", difficulty: "hard", question: "Was bedeutet 'Einsturzgefahr' in Bezug auf Lost Places?", answers: ["Das Gebäude wird bald abgerissen", "Teile des Gebäudes können jederzeit einstürzen", "Es gibt Einbrecher", "Das Dach ist undicht"], correct: 1, explanation: "Morsche Balken und instabile Strukturen können zum Einsturz führen - höchste Vorsicht!" },
    { id: 12, category: "Sicherheit", difficulty: "medium", question: "Warum solltest du jemandem mitteilen, wohin du gehst?", answers: ["Damit sie mitkommen können", "Falls du nicht zurückkommst, kann man dich suchen", "Für Social Media Posts", "Ist nicht nötig"], correct: 1, explanation: "Im Notfall weiß jemand, wo du bist und kann Hilfe schicken." },

    // RECHTLICHES
    { id: 13, category: "Rechtliches", difficulty: "medium", question: "Was ist Hausfriedensbruch?", answers: ["Ein Einbruch mit Diebstahl", "Das unbefugte Betreten eines Grundstücks", "Vandalismus", "Fotografieren ohne Erlaubnis"], correct: 1, explanation: "Hausfriedensbruch ist das Betreten eines Grundstücks ohne Erlaubnis des Eigentümers." },
    { id: 14, category: "Rechtliches", difficulty: "hard", question: "Welche Strafe kann bei Hausfriedensbruch drohen?", answers: ["Nur Verwarnung", "Geldstrafe oder bis zu einem Jahr Freiheitsstrafe", "Lebenslänglich", "Keine Strafe"], correct: 1, explanation: "Hausfriedensbruch ist eine Straftat nach § 123 StGB mit Geld- oder Freiheitsstrafe." },
    { id: 15, category: "Rechtliches", difficulty: "easy", question: "Ist das Fotografieren in Lost Places erlaubt?", answers: ["Immer erlaubt", "Nur mit Genehmigung des Eigentümers", "Nur für Journalisten", "Nur bei Tag"], correct: 1, explanation: "Das Fotografieren auf fremdem Eigentum benötigt grundsätzlich eine Genehmigung." },
    { id: 16, category: "Rechtliches", difficulty: "medium", question: "Was bedeutet 'Betreten verboten'-Schilder rechtlich?", answers: ["Nur eine Empfehlung", "Ignorieren ist erlaubt", "Der Eigentümer verbietet den Zutritt ausdrücklich", "Gilt nur für Kinder"], correct: 2, explanation: "Das Schild dokumentiert, dass der Zutritt untersagt ist - Betreten ist dann strafbar." },
    { id: 17, category: "Rechtliches", difficulty: "hard", question: "Darf man Gegenstände aus Lost Places mitnehmen?", answers: ["Ja, sie sind ja verlassen", "Nein, das ist Diebstahl", "Nur kleine Dinge", "Nur wenn niemand zusieht"], correct: 1, explanation: "Auch in verlassenen Gebäuden gehört alles jemandem - Mitnehmen ist Diebstahl!" },

    // GESCHICHTE
    { id: 18, category: "Geschichte", difficulty: "medium", question: "Welcher berühmte Lost Place liegt in der Ukraine?", answers: ["Beelitz-Heilstätten", "Tschernobyl/Prypjat", "Hashima Island", "Kolmanskop"], correct: 1, explanation: "Prypjat wurde 1986 nach der Tschernobyl-Katastrophe evakuiert und ist ein bekannter Lost Place." },
    { id: 19, category: "Geschichte", difficulty: "hard", question: "Was waren die Beelitz-Heilstätten ursprünglich?", answers: ["Ein Gefängnis", "Ein Sanatorium für Tuberkulose-Patienten", "Eine Munitionsfabrik", "Ein Hotel"], correct: 1, explanation: "Die Beelitz-Heilstätten waren ab 1898 ein Lungensanatorium nahe Berlin." },
    { id: 20, category: "Geschichte", difficulty: "medium", question: "Warum wurde die japanische Insel Hashima (Gunkanjima) verlassen?", answers: ["Tsunami", "Die Kohleminen wurden unrentabel", "Krieg", "Vulkanausbruch"], correct: 1, explanation: "Die Insel wurde verlassen, als Japan auf Erdöl umstieg und die Kohleförderung einstellte." },
    { id: 21, category: "Geschichte", difficulty: "hard", question: "In welchem Jahr wurde der Freizeitpark Spreepark Berlin geschlossen?", answers: ["1995", "2002", "2010", "1989"], correct: 1, explanation: "Der Spreepark wurde 2002 geschlossen und ist seitdem ein bekannter Lost Place." },
    { id: 22, category: "Geschichte", difficulty: "medium", question: "Was ist Kolmanskop in Namibia?", answers: ["Ein Lost Place in der Wüste", "Eine verlassene Diamantenstadt", "Ein altes Fort", "Ein Flugzeugfriedhof"], correct: 1, explanation: "Kolmanskop war eine deutsche Diamantenstadt, die in den 1950ern aufgegeben wurde." },

    // PRAXIS
    { id: 23, category: "Praxis", difficulty: "easy", question: "Wann ist die beste Tageszeit für Urbex?", answers: ["Nachts für Spannung", "Tagsüber wegen Sicherheit und Licht", "Egal", "Nur bei Vollmond"], correct: 1, explanation: "Tageslicht ermöglicht bessere Erkundung und Gefahren sind leichter erkennbar." },
    { id: 24, category: "Praxis", difficulty: "medium", question: "Warum sollte man Lost Place Locations nicht öffentlich teilen?", answers: ["Ist illegal", "Schützt vor Vandalismus und Überfüllung", "Die Orte sind geheim", "Man kann sie verkaufen"], correct: 1, explanation: "Öffentliche Locations werden oft vandalisiert oder zugemüllt." },
    { id: 25, category: "Praxis", difficulty: "easy", question: "Was solltest du tun, wenn du andere Personen im Lost Place triffst?", answers: ["Weglaufen", "Freundlich grüßen und respektvoll verhalten", "Verstecken", "Polizei rufen"], correct: 1, explanation: "Die meisten sind ebenfalls Explorer - ein freundlicher Umgang ist wichtig." },
    { id: 26, category: "Praxis", difficulty: "hard", question: "Was ist 'Infiltration' im Urbex-Kontext?", answers: ["Wassereinbruch", "Das heimliche Betreten von aktiven Gebäuden", "Eine Kameratechnik", "Ein Sicherheitssystem"], correct: 1, explanation: "Infiltration bezeichnet das Betreten aktiver Gebäude - sehr riskant und illegal!" },
    { id: 27, category: "Praxis", difficulty: "medium", question: "Welche App kann bei der Vorbereitung helfen?", answers: ["TikTok", "Google Maps/Earth für Recherche", "Candy Crush", "Tinder"], correct: 1, explanation: "Google Maps hilft bei der Recherche von Zugängen und der Umgebung." },
    { id: 28, category: "Praxis", difficulty: "easy", question: "Was ist ein 'Tourer' im Urbex?", answers: ["Ein Reisebus", "Jemand der oft und viel exploriert", "Ein Touristenführer", "Eine spezielle Kamera"], correct: 1, explanation: "Tourer sind erfahrene Explorer, die regelmäßig viele Orte besuchen." },
    { id: 29, category: "Praxis", difficulty: "hard", question: "Was bedeutet 'Hot Spot' im Urbex-Jargon?", answers: ["Ein Ort mit WLAN", "Ein oft besuchter, bekannter Lost Place", "Ein gefährlicher Bereich", "Ein Fotostandort"], correct: 1, explanation: "Hot Spots sind sehr bekannte Locations, die oft überlaufen und vandalisiert sind." },
    { id: 30, category: "Praxis", difficulty: "medium", question: "Warum tragen manche Urbexer dunkle Kleidung?", answers: ["Modestil", "Um unauffällig zu bleiben", "Gegen Staub", "Vorschrift"], correct: 1, explanation: "Dunkle Kleidung macht Explorer weniger auffällig für Anwohner oder Sicherheitsdienste." },

    // EXPERT LEVEL - Sehr schwere Fragen für erfahrene Urbexer
    { id: 31, category: "Geschichte", difficulty: "expert", question: "In welchem Jahr wurde der Freizeitpark Nara Dreamland in Japan endgültig abgerissen?", answers: ["2016", "2017", "2020", "2014"], correct: 1, explanation: "Nara Dreamland wurde 2017 abgerissen, nachdem er 2006 geschlossen wurde." },
    { id: 32, category: "Sicherheit", difficulty: "expert", question: "Welche Atemschutzmaske-Klassifizierung ist für Asbestfasern geeignet?", answers: ["FFP1", "FFP2", "FFP3 oder P100", "Stoffmaske"], correct: 2, explanation: "Nur FFP3- oder P100-Masken filtern feine Asbestfasern zuverlässig." },
    { id: 33, category: "Rechtliches", difficulty: "expert", question: "Wie lange beträgt die Verjährungsfrist für Hausfriedensbruch in Deutschland?", answers: ["3 Monate", "3 Jahre", "5 Jahre", "10 Jahre"], correct: 1, explanation: "Die Verjährungsfrist für Hausfriedensbruch beträgt 3 Jahre nach § 78 StGB." },
    { id: 34, category: "Geschichte", difficulty: "expert", question: "Welches Hospital diente als Drehort für 'A Cure for Wellness'?", answers: ["Beelitz-Heilstätten", "Charité Berlin", "Heilstätten Hohenlychen", "Klinikum Westend"], correct: 0, explanation: "Die Beelitz-Heilstätten dienten als Kulisse für den Film 'A Cure for Wellness' (2016)." },
    { id: 35, category: "Sicherheit", difficulty: "expert", question: "Was ist PCB und warum ist es in alten Gebäuden gefährlich?", answers: ["Ein Pestizid", "Ein giftiger Baustoff in Fugenmassen und Transformatoren", "Ein Schimmelpilz", "Ein explosives Gas"], correct: 1, explanation: "PCB (Polychlorierte Biphenyle) wurde in Fugenmassen und Elektrogeräten verwendet und ist krebserregend." },
    { id: 36, category: "Praxis", difficulty: "expert", question: "Was bedeutet 'Layering' im Urbex-Kontext?", answers: ["Mehrere Kamerafilter nutzen", "Mehrere Kleidungsschichten für Temperaturwechsel", "Fotos übereinanderlegen", "Mehrere Ausgänge planen"], correct: 1, explanation: "Layering bedeutet mehrere Kleidungsschichten zu tragen, da Temperaturen in Lost Places stark variieren." },
    { id: 37, category: "Geschichte", difficulty: "expert", question: "Welche ehemalige Olympiastadt hat einen berühmten verlassenen Sportkomplex?", answers: ["Athen", "Berlin", "München", "London"], correct: 0, explanation: "Die Olympiastätten von Athen 2004 verfallen größtenteils und sind bekannte Lost Places." },
    { id: 38, category: "Sicherheit", difficulty: "expert", question: "Was ist bei der Erkundung ehemaliger Militäranlagen besonders zu beachten?", answers: ["Nur nachts gehen", "Mögliche Munitionsreste und Kampfmittel", "Immer Uniform tragen", "GPS ausschalten"], correct: 1, explanation: "Alte Militärgelände können Blindgänger und Munitionsreste enthalten - höchste Gefahr!" },
    { id: 39, category: "Rechtliches", difficulty: "expert", question: "Welcher Paragraf regelt in Deutschland die Sachbeschädigung?", answers: ["§ 123 StGB", "§ 242 StGB", "§ 303 StGB", "§ 185 StGB"], correct: 2, explanation: "§ 303 StGB regelt die Sachbeschädigung, die bei Urbex oft relevant wird." },
    { id: 40, category: "Praxis", difficulty: "expert", question: "Was ist ein 'Recce' im Urbex-Jargon?", answers: ["Eine Kameramarke", "Eine Vorerkundung des Geländes", "Ein Fluchtweg", "Ein Sicherheitsschloss"], correct: 1, explanation: "Recce (von Reconnaissance) bezeichnet eine Vorerkundung zur Planung des eigentlichen Besuchs." },

    // MASTER LEVEL - Die schwierigsten Fragen für absolute Profis
    { id: 41, category: "Geschichte", difficulty: "master", question: "Wie hieß der Architekt der Beelitz-Heilstätten?", answers: ["Heino Schmieden", "Walter Gropius", "Peter Behrens", "Ludwig Mies van der Rohe"], correct: 0, explanation: "Heino Schmieden entwarf die Beelitz-Heilstätten im Pavillonstil Ende des 19. Jahrhunderts." },
    { id: 42, category: "Sicherheit", difficulty: "master", question: "Welche Wellenlänge hat ein typischer CO-Detektor für tragbare Gaswarner?", answers: ["Infrarot um 4.6 µm", "UV um 250 nm", "Elektrochemisch - keine Wellenlänge", "Mikrowelle"], correct: 2, explanation: "Tragbare CO-Detektoren arbeiten elektrochemisch, nicht optisch." },
    { id: 43, category: "Geschichte", difficulty: "master", question: "In welchem Jahr wurde Pripyat gegründet?", answers: ["1970", "1967", "1975", "1980"], correct: 0, explanation: "Pripyat wurde 1970 als Atomstadt für die Arbeiter von Tschernobyl gegründet." },
    { id: 44, category: "Rechtliches", difficulty: "master", question: "Welche Bedingung macht aus Hausfriedensbruch einen 'schweren Fall'?", answers: ["Nachtzeit", "Waffe mitführen oder Widerstand gegen Berechtigte", "Wiederholungstat", "Minderjährigkeit"], correct: 1, explanation: "Das Mitführen von Waffen oder Widerstand verschärft den Hausfriedensbruch erheblich." },
    { id: 45, category: "Praxis", difficulty: "master", question: "Was ist 'Buildering' und wie unterscheidet es sich von Urbex?", answers: ["Ein Baustil", "Klettern an Gebäudefassaden ohne Sicherung", "Fotografietechnik", "Kartografie von Gebäuden"], correct: 1, explanation: "Buildering ist das Klettern an Gebäudefassaden - noch riskanter als klassisches Urbex." },
    { id: 46, category: "Geschichte", difficulty: "master", question: "Welches berühmte Sanatorium in Georgien wurde 1950 erbaut und gilt als architektonisches Meisterwerk?", answers: ["Sanatorium Druschba", "Rixos Borjomi", "Likani Palace", "Tskaltubo Spa"], correct: 0, explanation: "Das Sanatorium Druschba in Jalta ist ein ikonisches Beispiel sowjetischer Architektur." },
    { id: 47, category: "Sicherheit", difficulty: "master", question: "Welcher Sauerstoffgehalt in der Luft gilt als lebensbedrohlich niedrig?", answers: ["Unter 21%", "Unter 19.5%", "Unter 16%", "Unter 12%"], correct: 2, explanation: "Ab unter 16% Sauerstoff treten schwere Symptome auf, unter 6% ist es tödlich." },
    { id: 48, category: "Rechtliches", difficulty: "master", question: "Was ist der Unterschied zwischen Hausfriedensbruch und Landfriedensbruch?", answers: ["Kein Unterschied", "Hausfriedensbruch = Gebäude, Landfriedensbruch = Gewalt in Menschenmengen", "Nur die Strafe unterscheidet sich", "Landfriedensbruch gilt nur auf Land"], correct: 1, explanation: "Landfriedensbruch (§125 StGB) betrifft Gewalttaten aus Menschenmengen heraus - ganz anderes Delikt." },
    { id: 49, category: "Geschichte", difficulty: "master", question: "Welche verlassene Stadt in Zypern ist seit 1974 gesperrt?", answers: ["Limassol", "Varosha/Famagusta", "Paphos", "Larnaca"], correct: 1, explanation: "Varosha wurde 1974 nach der türkischen Invasion evakuiert und ist seitdem Sperrgebiet." },
    { id: 50, category: "Praxis", difficulty: "master", question: "Was versteht man unter 'Drain Exploration' oder 'Draining'?", answers: ["Entwässerung von Gebäuden", "Erkundung von Abwasserkanälen und unterirdischen Wasserführungen", "Dokumentation von Wasserschäden", "Tauchen in überschwemmten Kellern"], correct: 1, explanation: "Draining ist die Erkundung von Kanalisationen und Entwässerungssystemen - extrem gefährlich wegen Sturzfluten." }
];

// Export für Verwendung in app.js
if (typeof module !== 'undefined' && module.exports) {
    module.exports = quizQuestions;
}
